# Generated by Django 6.1.1 on 2026-09-18 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Имя файла')),
                ('backend', models.CharField(blank=True, max_length=32, verbose_name='Бэкенд')),
                ('risk_level', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('unknown', 'Не определён')], default='unknown', max_length=16, verbose_name='Уровень риска')),
                ('needs_human_review', models.BooleanField(default=False, verbose_name='Нужна проверка человеком')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('raw_report', models.JSONField(default=dict, verbose_name='Полный отчёт (JSON)')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата анализа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Результат анализа',
                'verbose_name_plural': 'Результаты анализа',
                'ordering': ['-created_at'],
            },
        ),
    ]
